rootProject.name = 'shopkeepers'

def subprojects = [
	'external-annotations',
	'api',
	'main',
	'v1_21_R4_paper',
	'v1_21_R5',
	'v1_21_R5_paper',
	'v1_21_R6',
	'v1_21_R6_paper',
	'v1_21_R7',
	'v1_21_R7_paper',
	'v1_21_R8',
	'v1_21_R8_paper',
	'v1_21_R9',
	'v1_21_R9_paper',
	'v26_1_R1',
	'v26_1_R1_paper',
	'v26_2_R1',
	'v26_2_R1_paper',
	'test',
	'dist'
]

subprojects.each { subproject ->
	include subproject
	project(":${subproject}").projectDir = file("modules/${subproject}")
	project(":${subproject}").name = "shopkeepers-${subproject}"
}
